
/*
 * Copyright (c) 2008 - 2012, Andy Bierman, All Rights Reserved.
 * Copyright (c) 2012 - 2022, YumaWorks, Inc., All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

/**
 * @file y_Amantya-NIAB-5gsacore.c
 * @brief YumaPro SIL module for module Amantya-NIAB-5gsacore
 *

*** Generated by yangdump-sdk 21.10-5

<pre>

    YumaPro SIL module
    module Amantya-NIAB-5gsacore
    revision 2022-12-15
    prefix amantya-niab
    namespace http://amantyatech.com/ns/yang/Amantya-NIAB-5gsacore
    organization Amantya Technologies
    Created: 2023-01-30T06:01:43Z

Online Developer Manual:
https://www.yumaworks.com/pub/21.10/dev/yumapro-dev-manual.html

    CLI parameters:
        format yc
        indent 4
        module Amantya-NIAB-5gsacore
        output y_Amantya-NIAB-5gsacore.c
        unified true

  Short Name Mappings
    af = /niab/af
    alarmSource = /alarms/input/alarmSource
    alarmSource_1 = /niab_containers_amf/alarmSource
    alarmSource_10 = /niab_containers_af/alarmSource
    alarmSource_11 = /niab_containers_bsf/alarmSource
    alarmSource_12 = /niab_containers_udm/alarmSource
    alarmSource_2 = /niab_containers_gnb/alarmSource
    alarmSource_3 = /niab_containers_upf/alarmSource
    alarmSource_4 = /niab_containers_smf/alarmSource
    alarmSource_5 = /niab_containers_nrf/alarmSource
    alarmSource_6 = /niab_containers_ausf/alarmSource
    alarmSource_7 = /niab_containers_nssf/alarmSource
    alarmSource_8 = /niab_containers_nef/alarmSource
    alarmSource_9 = /niab_containers_pcf/alarmSource
    alarmType = /alarms/input/alarmType
    alarmType_1 = /niab_containers_amf/alarmType
    alarmType_10 = /niab_containers_af/alarmType
    alarmType_11 = /niab_containers_bsf/alarmType
    alarmType_12 = /niab_containers_udm/alarmType
    alarmType_2 = /niab_containers_gnb/alarmType
    alarmType_3 = /niab_containers_upf/alarmType
    alarmType_4 = /niab_containers_smf/alarmType
    alarmType_5 = /niab_containers_nrf/alarmType
    alarmType_6 = /niab_containers_ausf/alarmType
    alarmType_7 = /niab_containers_nssf/alarmType
    alarmType_8 = /niab_containers_nef/alarmType
    alarmType_9 = /niab_containers_pcf/alarmType
    alarms = /alarms
    amf = /niab/amf
    ausf = /niab/ausf
    bsf = /niab/bsf
    change_contanier_state = /change-contanier-state
    changedState = /alarms/input/changedState
    changedState_1 = /niab_containers_amf/changedState
    changedState_10 = /niab_containers_af/changedState
    changedState_11 = /niab_containers_bsf/changedState
    changedState_12 = /niab_containers_udm/changedState
    changedState_2 = /niab_containers_gnb/changedState
    changedState_3 = /niab_containers_upf/changedState
    changedState_4 = /niab_containers_smf/changedState
    changedState_5 = /niab_containers_nrf/changedState
    changedState_6 = /niab_containers_ausf/changedState
    changedState_7 = /niab_containers_nssf/changedState
    changedState_8 = /niab_containers_nef/changedState
    changedState_9 = /niab_containers_pcf/changedState
    clearAlarm = /alarms/input/clearAlarm
    clearAlarm_1 = /niab_containers_amf/clearAlarm
    clearAlarm_10 = /niab_containers_af/clearAlarm
    clearAlarm_11 = /niab_containers_bsf/clearAlarm
    clearAlarm_12 = /niab_containers_udm/clearAlarm
    clearAlarm_2 = /niab_containers_gnb/clearAlarm
    clearAlarm_3 = /niab_containers_upf/clearAlarm
    clearAlarm_4 = /niab_containers_smf/clearAlarm
    clearAlarm_5 = /niab_containers_nrf/clearAlarm
    clearAlarm_6 = /niab_containers_ausf/clearAlarm
    clearAlarm_7 = /niab_containers_nssf/clearAlarm
    clearAlarm_8 = /niab_containers_nef/clearAlarm
    clearAlarm_9 = /niab_containers_pcf/clearAlarm
    containerState = /change-contanier-state/input/containerState
    containerType = /edit-niab/input/containerType
    containerType_1 = /change-contanier-state/input/containerType
    description = /alarms/input/description
    description_1 = /niab_containers_amf/description
    description_10 = /niab_containers_af/description
    description_11 = /niab_containers_bsf/description
    description_12 = /niab_containers_udm/description
    description_2 = /niab_containers_gnb/description
    description_3 = /niab_containers_upf/description
    description_4 = /niab_containers_smf/description
    description_5 = /niab_containers_nrf/description
    description_6 = /niab_containers_ausf/description
    description_7 = /niab_containers_nssf/description
    description_8 = /niab_containers_nef/description
    description_9 = /niab_containers_pcf/description
    discover_device = /discover-device
    edit_niab = /edit-niab
    fileUpdated = /updateConfigurtion/fileUpdated
    gnb = /niab/gnb
    hw_version = /discover-device/input/hw_version
    hw_version_1 = /register-device/hw_version
    impactedEntity = /alarms/input/impactedEntity
    input = /discover-device/input
    input_1 = /edit-niab/input
    input_2 = /alarms/input
    input_3 = /change-contanier-state/input
    ip_add = /discover-device/input/ip_add
    ip_add_1 = /register-device/ip_add
    is_device_added = /discover-device/input/is_device_added
    is_device_added_1 = /register-device/is_device_added
    manufacturer = /discover-device/input/manufacturer
    manufacturer_1 = /register-device/manufacturer
    name = /discover-device/input/name
    name_1 = /register-device/name
    nef = /niab/nef
    newConfig = /edit-niab/input/newConfig
    niab = /niab
    niab_containers_af = /niab_containers_af
    niab_containers_amf = /niab_containers_amf
    niab_containers_ausf = /niab_containers_ausf
    niab_containers_bsf = /niab_containers_bsf
    niab_containers_gnb = /niab_containers_gnb
    niab_containers_nef = /niab_containers_nef
    niab_containers_nrf = /niab_containers_nrf
    niab_containers_nssf = /niab_containers_nssf
    niab_containers_pcf = /niab_containers_pcf
    niab_containers_smf = /niab_containers_smf
    niab_containers_udm = /niab_containers_udm
    niab_containers_upf = /niab_containers_upf
    nrf = /niab/nrf
    nssf = /niab/nssf
    oldConfig = /edit-niab/input/oldConfig
    output = /discover-device/output
    output_1 = /edit-niab/output
    output_2 = /alarms/output
    output_3 = /change-contanier-state/output
    password = /discover-device/input/password
    password_1 = /register-device/password
    pcf = /niab/pcf
    port = /discover-device/input/port
    port_1 = /register-device/port
    register_device = /register-device
    serial = /discover-device/input/serial
    serial_1 = /register-device/serial
    severity = /alarms/input/severity
    severity_1 = /niab_containers_amf/severity
    severity_10 = /niab_containers_af/severity
    severity_11 = /niab_containers_bsf/severity
    severity_12 = /niab_containers_udm/severity
    severity_2 = /niab_containers_gnb/severity
    severity_3 = /niab_containers_upf/severity
    severity_4 = /niab_containers_smf/severity
    severity_5 = /niab_containers_nrf/severity
    severity_6 = /niab_containers_ausf/severity
    severity_7 = /niab_containers_nssf/severity
    severity_8 = /niab_containers_nef/severity
    severity_9 = /niab_containers_pcf/severity
    smf = /niab/smf
    sw_version = /discover-device/input/sw_version
    sw_version_1 = /register-device/sw_version
    timeRaised = /alarms/input/timeRaised
    timeRaised_1 = /niab_containers_amf/timeRaised
    timeRaised_10 = /niab_containers_af/timeRaised
    timeRaised_11 = /niab_containers_bsf/timeRaised
    timeRaised_12 = /niab_containers_udm/timeRaised
    timeRaised_2 = /niab_containers_gnb/timeRaised
    timeRaised_3 = /niab_containers_upf/timeRaised
    timeRaised_4 = /niab_containers_smf/timeRaised
    timeRaised_5 = /niab_containers_nrf/timeRaised
    timeRaised_6 = /niab_containers_ausf/timeRaised
    timeRaised_7 = /niab_containers_nssf/timeRaised
    timeRaised_8 = /niab_containers_nef/timeRaised
    timeRaised_9 = /niab_containers_pcf/timeRaised
    type = /discover-device/input/type
    type_1 = /register-device/type
    udm = /niab/udm
    updateConfigurtion = /updateConfigurtion
    upf = /niab/upf
    user = /discover-device/input/user
    user_1 = /register-device/user
</pre>

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_action.h"
#include "agt_cb.h"
#include "agt_cfg.h"
#include "agt_not.h"
#include "agt_rpc.h"
#include "agt_sil_lib.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "agt_val.h"
#include "cfg.h"
#include "dlq.h"
#include "getcb.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "obj.h"
#include "rpc.h"
#include "ses.h"
#include "status.h"
#include "val.h"
#include "val_child.h"
#include "val_util.h"
#include "xml_util.h"
#include "xml_val.h"
#include "u_Amantya-NIAB-5gsacore.h"
#include "y_Amantya-NIAB-5gsacore.h"


/**
 * @addtogroup yang-library YANG Library
 *
 * Collection of modules supported by the server.
 * Generated by yangdump-sdk.
 */



/**
 * @addtogroup sil-Amantya-NIAB-5gsacore Module Amantya-NIAB-5gsacore
 * @ingroup yang-library
 *
 * @{
 *
 * YANG instrumentation library.
 * Generated by yangdump-sdk.
 */


/* module static variables */
static ncx_module_t *Amantya_NIAB_5gsacore_mod;
static obj_template_t *niab_obj;
static obj_template_t *discover_device_obj;
static obj_template_t *edit_niab_obj;
static obj_template_t *alarms_obj;
static obj_template_t *change_contanier_state_obj;
static val_value_t *niab_val;

/**
 * @brief Initialize module static variables
 *
 * Called by server when module is loaded.
 */
static void y_amantya_niab_init_static_vars (void)
{
    Amantya_NIAB_5gsacore_mod = NULL;
    niab_obj = NULL;
    discover_device_obj = NULL;
    edit_niab_obj = NULL;
    alarms_obj = NULL;
    change_contanier_state_obj = NULL;
    niab_val = NULL;

} /* y_amantya_niab_init_static_vars */


/**
 * @brief Get database object callback for leaf gnb (getcb_fn2_t)\n
 * Path: leaf /niab/gnb\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t gnb_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter gnb_get");
    }

    (void)scb;
    (void)msg;

    return u_amantya_niab_gnb_get(get2cb);

} /* gnb_get */


/**
 * @brief Get database object callback for leaf amf (getcb_fn2_t)\n
 * Path: leaf /niab/amf\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t amf_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter amf_get");
    }

    (void)scb;
    (void)msg;

    return u_amantya_niab_amf_get(get2cb);

} /* amf_get */


/**
 * @brief Get database object callback for leaf smf (getcb_fn2_t)\n
 * Path: leaf /niab/smf\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t smf_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter smf_get");
    }

    (void)scb;
    (void)msg;

    return u_amantya_niab_smf_get(get2cb);

} /* smf_get */


/**
 * @brief Get database object callback for leaf upf (getcb_fn2_t)\n
 * Path: leaf /niab/upf\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t upf_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter upf_get");
    }

    (void)scb;
    (void)msg;

    return u_amantya_niab_upf_get(get2cb);

} /* upf_get */


/**
 * @brief Get database object callback for leaf nrf (getcb_fn2_t)\n
 * Path: leaf /niab/nrf\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t nrf_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter nrf_get");
    }

    (void)scb;
    (void)msg;

    return u_amantya_niab_nrf_get(get2cb);

} /* nrf_get */


/**
 * @brief Get database object callback for leaf ausf (getcb_fn2_t)\n
 * Path: leaf /niab/ausf\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t ausf_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter ausf_get");
    }

    (void)scb;
    (void)msg;

    return u_amantya_niab_ausf_get(get2cb);

} /* ausf_get */


/**
 * @brief Get database object callback for leaf nssf (getcb_fn2_t)\n
 * Path: leaf /niab/nssf\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t nssf_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter nssf_get");
    }

    (void)scb;
    (void)msg;

    return u_amantya_niab_nssf_get(get2cb);

} /* nssf_get */


/**
 * @brief Get database object callback for leaf nef (getcb_fn2_t)\n
 * Path: leaf /niab/nef\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t nef_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter nef_get");
    }

    (void)scb;
    (void)msg;

    return u_amantya_niab_nef_get(get2cb);

} /* nef_get */


/**
 * @brief Get database object callback for leaf pcf (getcb_fn2_t)\n
 * Path: leaf /niab/pcf\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t pcf_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter pcf_get");
    }

    (void)scb;
    (void)msg;

    return u_amantya_niab_pcf_get(get2cb);

} /* pcf_get */


/**
 * @brief Get database object callback for leaf af (getcb_fn2_t)\n
 * Path: leaf /niab/af\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t af_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter af_get");
    }

    (void)scb;
    (void)msg;

    return u_amantya_niab_af_get(get2cb);

} /* af_get */


/**
 * @brief Get database object callback for leaf bsf (getcb_fn2_t)\n
 * Path: leaf /niab/bsf\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t bsf_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter bsf_get");
    }

    (void)scb;
    (void)msg;

    return u_amantya_niab_bsf_get(get2cb);

} /* bsf_get */


/**
 * @brief Get database object callback for leaf udm (getcb_fn2_t)\n
 * Path: leaf /niab/udm\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t udm_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter udm_get");
    }

    (void)scb;
    (void)msg;

    return u_amantya_niab_udm_get(get2cb);

} /* udm_get */


/**
 * @brief Edit database object callback (agt_cb_fn_t)\n
 * Path: container /niab
 *
 * @param scb session control block making the request
 * @param msg message in progress for this edit request
 * @param cbtyp callback type for this callback
 * @param editop the parent edit-config operation type,
 * which is also used for all other callbacks
 * that operate on objects.
 * @param newval container object holding the proposed changes
 * to apply to the current config, depending on
 * the editop value. Will not be NULL.
 * @param curval current container values from the "<running>"
 * or "<candidate>" configuration, if any. Could be NULL
 * for create and other operations.
 * @return return status for the phase.
 */
static status_t niab_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    if (LOGDEBUG) {
        log_debug("\nEnter niab_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_amantya_niab_niab_edit(scb, msg, cbtyp, editop, newval, curval);

    if (res == NO_ERR && cbtyp == AGT_CB_COMMIT) {
        res = agt_check_cache(&niab_val, newval, curval, editop);
    }


    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* niab_edit */


/**
 * @brief Phase 1: Initialize the Amantya-NIAB-5gsacore server instrumentation library.
 *
 * Called by server when module is loaded.
 *
 * @param modname requested module name to load
 * @param revision requested revision date of the module to load.
 * This may be NULL if the module has no revision statements.
 * @return return status. An error will cause the module load to fail.
 */
status_t y_Amantya_NIAB_5gsacore_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter y_Amantya_NIAB_5gsacore_init");
    }


    y_amantya_niab_init_static_vars();

    /* change if custom handling done */
    if (xml_strcmp(modname, y_amantya_niab_M_amantya_niab)) {
        return ERR_NCX_UNKNOWN_MODULE;
    }

    if (revision && xml_strcmp(revision, y_amantya_niab_R_amantya_niab)) {
        return ERR_NCX_WRONG_VERSION;
    }

    res = ncxmod_load_module(
        y_amantya_niab_M_amantya_niab,
        y_amantya_niab_R_amantya_niab,
        agt_get_savedevQ(),
        &Amantya_NIAB_5gsacore_mod);
    if (res != NO_ERR) {
        return res;
    }

    niab_obj = ncx_find_object(
        Amantya_NIAB_5gsacore_mod,
        y_amantya_niab_N_niab);
    if (niab_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    discover_device_obj = ncx_find_object(
        Amantya_NIAB_5gsacore_mod,
        y_amantya_niab_N_discover_device);
    if (discover_device_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    edit_niab_obj = ncx_find_object(
        Amantya_NIAB_5gsacore_mod,
        y_amantya_niab_N_edit_niab);
    if (edit_niab_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    alarms_obj = ncx_find_object(
        Amantya_NIAB_5gsacore_mod,
        y_amantya_niab_N_alarms);
    if (alarms_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    change_contanier_state_obj = ncx_find_object(
        Amantya_NIAB_5gsacore_mod,
        y_amantya_niab_N_change_contanier_state);
    if (change_contanier_state_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    res = agt_rpc_register_method(
        y_amantya_niab_M_amantya_niab,
        y_amantya_niab_N_discover_device,
        AGT_RPC_PH_VALIDATE,
        u_amantya_niab_discover_device_validate);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_amantya_niab_M_amantya_niab,
        y_amantya_niab_N_discover_device,
        AGT_RPC_PH_INVOKE,
        u_amantya_niab_discover_device_invoke);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_amantya_niab_M_amantya_niab,
        y_amantya_niab_N_edit_niab,
        AGT_RPC_PH_VALIDATE,
        u_amantya_niab_edit_niab_validate);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_amantya_niab_M_amantya_niab,
        y_amantya_niab_N_edit_niab,
        AGT_RPC_PH_INVOKE,
        u_amantya_niab_edit_niab_invoke);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_amantya_niab_M_amantya_niab,
        y_amantya_niab_N_alarms,
        AGT_RPC_PH_VALIDATE,
        u_amantya_niab_alarms_validate);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_amantya_niab_M_amantya_niab,
        y_amantya_niab_N_alarms,
        AGT_RPC_PH_INVOKE,
        u_amantya_niab_alarms_invoke);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_amantya_niab_M_amantya_niab,
        y_amantya_niab_N_change_contanier_state,
        AGT_RPC_PH_VALIDATE,
        u_amantya_niab_change_contanier_state_validate);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_amantya_niab_M_amantya_niab,
        y_amantya_niab_N_change_contanier_state,
        AGT_RPC_PH_INVOKE,
        u_amantya_niab_change_contanier_state_invoke);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_edit2_callback(
        y_amantya_niab_M_amantya_niab,
        (const xmlChar *)"/amantya-niab:niab",
        y_amantya_niab_R_amantya_niab,
        niab_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_amantya_niab_M_amantya_niab,
        (const xmlChar *)"/amantya-niab:niab/amantya-niab:gnb",
        y_amantya_niab_R_amantya_niab,
        gnb_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_amantya_niab_M_amantya_niab,
        (const xmlChar *)"/amantya-niab:niab/amantya-niab:amf",
        y_amantya_niab_R_amantya_niab,
        amf_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_amantya_niab_M_amantya_niab,
        (const xmlChar *)"/amantya-niab:niab/amantya-niab:smf",
        y_amantya_niab_R_amantya_niab,
        smf_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_amantya_niab_M_amantya_niab,
        (const xmlChar *)"/amantya-niab:niab/amantya-niab:upf",
        y_amantya_niab_R_amantya_niab,
        upf_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_amantya_niab_M_amantya_niab,
        (const xmlChar *)"/amantya-niab:niab/amantya-niab:nrf",
        y_amantya_niab_R_amantya_niab,
        nrf_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_amantya_niab_M_amantya_niab,
        (const xmlChar *)"/amantya-niab:niab/amantya-niab:ausf",
        y_amantya_niab_R_amantya_niab,
        ausf_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_amantya_niab_M_amantya_niab,
        (const xmlChar *)"/amantya-niab:niab/amantya-niab:nssf",
        y_amantya_niab_R_amantya_niab,
        nssf_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_amantya_niab_M_amantya_niab,
        (const xmlChar *)"/amantya-niab:niab/amantya-niab:nef",
        y_amantya_niab_R_amantya_niab,
        nef_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_amantya_niab_M_amantya_niab,
        (const xmlChar *)"/amantya-niab:niab/amantya-niab:pcf",
        y_amantya_niab_R_amantya_niab,
        pcf_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_amantya_niab_M_amantya_niab,
        (const xmlChar *)"/amantya-niab:niab/amantya-niab:af",
        y_amantya_niab_R_amantya_niab,
        af_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_amantya_niab_M_amantya_niab,
        (const xmlChar *)"/amantya-niab:niab/amantya-niab:bsf",
        y_amantya_niab_R_amantya_niab,
        bsf_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_amantya_niab_M_amantya_niab,
        (const xmlChar *)"/amantya-niab:niab/amantya-niab:udm",
        y_amantya_niab_R_amantya_niab,
        udm_get);
    if (res != NO_ERR) {
        return res;
    }

    res = u_Amantya_NIAB_5gsacore_init(modname, revision);
    return res;

} /* y_Amantya_NIAB_5gsacore_init */


/**
 * @brief Phase 2: Initialize the Amantya-NIAB-5gsacore server instrumentation library.
 *
 * SIL init phase 2: non-config data structures.
 * Called after running config is loaded.
 *
 * @return return status. An error will cause the
 * server initialization to fail.
 */
status_t y_Amantya_NIAB_5gsacore_init2 (void)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter y_Amantya_NIAB_5gsacore_init2");
    }


    niab_val = agt_init_cache(
        y_amantya_niab_M_amantya_niab,
        y_amantya_niab_N_niab,
        &res);
    if (res != NO_ERR) {
        return res;
    }

    res = u_Amantya_NIAB_5gsacore_init2();

    return res;

} /* y_Amantya_NIAB_5gsacore_init2 */


/**
 * @brief Cleanup the Amantya-NIAB-5gsacore server instrumentation library.
 *
 * Called by server when module is unloaded.
 *
 */
void y_Amantya_NIAB_5gsacore_cleanup (void)
{

    if (LOGDEBUG) {
        log_debug("\nEnter y_Amantya_NIAB_5gsacore_cleanup");
    }


    agt_rpc_unregister_method(
        y_amantya_niab_M_amantya_niab,
        y_amantya_niab_N_discover_device);

    agt_rpc_unregister_method(
        y_amantya_niab_M_amantya_niab,
        y_amantya_niab_N_edit_niab);

    agt_rpc_unregister_method(
        y_amantya_niab_M_amantya_niab,
        y_amantya_niab_N_alarms);

    agt_rpc_unregister_method(
        y_amantya_niab_M_amantya_niab,
        y_amantya_niab_N_change_contanier_state);

    agt_cb_unregister_callbacks(
        y_amantya_niab_M_amantya_niab,
        (const xmlChar *)"/amantya-niab:niab");
    u_Amantya_NIAB_5gsacore_cleanup();

} /* y_Amantya_NIAB_5gsacore_cleanup */


 /** @} */

/* END SIL y_Amantya-NIAB-5gsacore.c */
